#!/usr/bin/env node
import { Command } from 'commander';
import { optimizeProject } from './index';
import { generateHtmlReport } from './htmlReport';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs';
import { exec } from 'child_process';

// Detect project type
function detectProjectType(projectPath: string): 'react-native' | 'node' | 'unknown' {
  try {
    const packagePath = path.join(projectPath, 'package.json');
    if (fs.existsSync(packagePath)) {
      const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
      
      // Check dependencies for React Native
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      if (deps['react-native'] || deps['@react-native/cli'] || deps['@react-native-community/cli'] ||
          deps['expo'] || deps['@expo/cli']) {
        return 'react-native';
      }
      
      // Check for React Native config files
      if (fs.existsSync(path.join(projectPath, 'metro.config.js')) ||
          fs.existsSync(path.join(projectPath, 'react-native.config.js')) ||
          fs.existsSync(path.join(projectPath, 'app.json')) ||
          fs.existsSync(path.join(projectPath, 'android')) ||
          fs.existsSync(path.join(projectPath, 'ios'))) {
        return 'react-native';
      }
      
      // Check for Node.js specific patterns
      if (deps['express'] || deps['fastify'] || deps['koa'] || 
          deps['prisma'] || deps['sequelize'] || deps['typeorm'] ||
          pkg.main || pkg.bin) {
        return 'node';
      }
    }
  } catch (e) {
    // Ignore errors
  }
  
  return 'unknown';
}

const program = new Command();

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function formatTime(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function printSeparator() {
  console.log(chalk.gray('─'.repeat(60)));
}

program
  .name('rnopt')
  .description('🚀 React Native Optimizer - Analyze and optimize React Native and Node.js projects')
  .version('0.1.0');

program
  .command('analyze')
  .description('Analyze React Native or Node.js project for optimization opportunities (includes package analysis and generates HTML report by default)')
  .option('-v, --verbose', 'Show detailed analysis information')
  .option('-o, --output <file>', 'Save report to JSON file')
  .option('--no-html', 'Skip HTML report generation (HTML is generated by default)')
  .option('--no-open', 'Skip auto-opening HTML report in browser (opens by default)')
  .option('--html-path <file>', 'Custom path for HTML report')
  .option('--build', 'Include build analysis (bundle size, dependencies)')
  .option('--no-packages', 'Skip package analysis (package analysis is included by default)')
  .option('--type <type>', 'Override project type detection (react-native|node)')
  .action(async (options) => {
    const projectPath = process.cwd();
    const projectName = path.basename(projectPath);
    
    console.log(chalk.bold.cyan('\n🔍 React Native Optimizer'));
    console.log(chalk.gray(`Analyzing project: ${chalk.white(projectName)}`));
    console.log(chalk.gray(`Location: ${projectPath}`));
    
    // Detect and show project type
    const projectType = detectProjectType(projectPath);
    const typeEmoji = projectType === 'react-native' ? '📱' : projectType === 'node' ? '🚀' : '📦';
    console.log(chalk.gray(`Project type: ${typeEmoji} ${chalk.white(projectType)}`));
    printSeparator();
    
    // Show enhanced modular progress with better user engagement
    let lastProgressLine = '';
    let lastModule = '';
    
    const progressCallback = (progress: any) => {
      const { 
        module, stage, current, total, percentage, currentItem, 
        timeElapsed, estimatedTimeRemaining, moduleProgress 
      } = progress;
      
      // Create overall progress bar
      const overallBarLength = 30;
      const overallFilled = Math.round((percentage / 100) * overallBarLength);
      const overallBar = '█'.repeat(overallFilled) + '░'.repeat(overallBarLength - overallFilled);
      
      // Create module progress bar
      const modulePercent = moduleProgress?.modulePercentage || 0;
      const moduleBarLength = 15;
      const moduleFilled = Math.round((modulePercent / 100) * moduleBarLength);
      const moduleBar = '▓'.repeat(moduleFilled) + '░'.repeat(moduleBarLength - moduleFilled);
      
      // Format timing info
      const elapsed = timeElapsed ? `${timeElapsed}s` : '--';
      const remaining = estimatedTimeRemaining && estimatedTimeRemaining > 0 ? `~${estimatedTimeRemaining}s` : '';
      
      // Module status indicator
      const moduleStatus = moduleProgress ? `[${moduleProgress.currentModule}/${moduleProgress.totalModules}]` : '';
      
      // Create main progress line
      let progressLine = `${chalk.cyan('🔄')} ${chalk.bold.white('Overall Progress')} ${chalk.cyan(`[${overallBar}]`)} ${chalk.bold.white(`${percentage}%`)}`;
      
      if (remaining) {
        progressLine += ` ${chalk.gray(`(${remaining} remaining)`)}`;
      } else {
        progressLine += ` ${chalk.gray(`(${elapsed} elapsed)`)}`;
      }
      
      // Add module-specific line
      progressLine += `\n${chalk.yellow('📋')} ${chalk.white(stage)}`;
      
      if (moduleProgress && modulePercent < 100) {
        progressLine += ` ${chalk.yellow(`[${moduleBar}]`)} ${chalk.white(`${modulePercent}%`)}`;
      }
      
      if (current > 0 && total > 1) {
        progressLine += ` ${chalk.gray(`(${current.toLocaleString()}/${total.toLocaleString()})`)}`;
      }
      
      if (moduleStatus) {
        progressLine += ` ${chalk.gray(moduleStatus)}`;
      }
      
      // Add current item being processed
      if (currentItem) {
        const displayItem = currentItem.length > 35 ? '...' + currentItem.slice(-32) : currentItem;
        progressLine += `\n${chalk.gray('   → ' + displayItem)}`;
      }
      
      // Show module transition
      if (module !== lastModule && lastModule) {
        const moduleNames: Record<string, string> = {
          'initialization': 'Initialization',
          'source-scan': 'Source Scanning', 
          'unused-imports': 'Import Analysis',
          'unused-files': 'File Analysis',
          'framework-detection': 'Framework Detection',
          'package-analysis': 'Package Analysis',
          'deprecated-check': 'Deprecation Check',
          'finalization': 'Finalization'
        };
        const moduleName = moduleNames[module] || module;
        progressLine += `\n${chalk.green('✓')} ${chalk.gray('Starting ' + moduleName + '...')}`;
      }
      
      lastModule = module;
      
      // Clear previous output and display new progress
      if (lastProgressLine) {
        const linesToClear = (lastProgressLine.match(/\n/g) || []).length + 1;
        process.stdout.write('\r\x1b[2K'); // Clear current line
        for (let i = 0; i < linesToClear; i++) {
          process.stdout.write('\x1b[1A\x1b[2K'); // Move cursor up and clear line
        }
      }
      
      process.stdout.write(progressLine);
      lastProgressLine = progressLine;
    };
    
    const result = await optimizeProject(projectPath, { 
      includeBuildAnalysis: options.build,
      includePackageAnalysis: options.packages !== false
    }, progressCallback);
    
    // Show final completion progress
    if (progressCallback) {
      progressCallback({
        module: 'finalization',
        stage: 'Analysis complete',
        current: 100,
        total: 100,
        percentage: 100,
        timeElapsed: Math.round((Date.now() - Date.now()) / 1000), // This will be updated by the progress tracker
        moduleProgress: {
          currentModule: 8,
          totalModules: 8,
          modulePercentage: 100
        }
      });
    }
    
    // Clear progress lines more thoroughly and reset
    if (lastProgressLine) {
      const linesToClear = (lastProgressLine.match(/\n/g) || []).length + 1;
      // Clear current line first
      process.stdout.write('\r\x1b[2K');
      // Clear all progress lines + some buffer
      for (let i = 0; i < linesToClear + 5; i++) { // Clear extra lines for safety
        process.stdout.write('\x1b[1A\x1b[2K');
      }
      // Reset progress tracking
      lastProgressLine = '';
    }
    
    // Add a clean newline to separate from any remaining artifacts
    console.log('');
    
    if (!result.success) {
      console.log(chalk.red.bold('\n❌ Analysis Failed'));
      result.issues.forEach(issue => {
        console.log(chalk.red(`   ${issue}`));
      });
      process.exit(1);
    }
    
    // Project Statistics
    console.log(chalk.bold.white('📊 Project Statistics'));
    console.log(`   Files analyzed: ${chalk.white(result.projectStats.totalFiles)}`);
    console.log(`   Total lines: ${chalk.white(result.projectStats.totalLines.toLocaleString())}`);
    console.log(`   Total size: ${chalk.white(formatBytes(result.projectStats.totalSize))}`);
    console.log(`   Analysis time: ${chalk.white(formatTime(result.projectStats.analysisTime))}`);
    printSeparator();
    
    // Unused Imports
    if (result.unusedImports.length > 0) {
      console.log(chalk.yellow.bold('⚠️  Unused Imports'));
      console.log(chalk.gray(`   Found ${result.unusedImports.length} file(s) with unused imports:`));
      result.unusedImports.forEach(item => {
        console.log(chalk.yellow(`   📄 ${item.file}`));
        item.imports.forEach(imp => {
          console.log(chalk.gray(`      • ${imp}`));
        });
      });
    } else {
      console.log(chalk.green.bold('✅ No unused imports found'));
    }
    printSeparator();
    
    // Unused Files
    if (result.unusedFiles.length > 0) {
      console.log(chalk.red.bold('🗑️  Unused Files (Code Debt)'));
      console.log(chalk.gray(`   Found ${result.unusedFiles.length} unused file(s):`));
      let totalWastedSize = 0;
      result.unusedFiles.forEach(file => {
        totalWastedSize += file.size;
        console.log(chalk.red(`   📄 ${file.path} ${chalk.gray(`(${formatBytes(file.size)}, ${file.lines} lines)`)}`));
      });
      console.log(chalk.gray(`   Total wasted space: ${chalk.red.bold(formatBytes(totalWastedSize))}`));
    } else {
      console.log(chalk.green.bold('✅ No unused files found'));
    }
    printSeparator();
    
    // Build Analysis
    if (result.buildAnalysis) {
      const build = result.buildAnalysis;
      console.log(chalk.magenta.bold('📦 Build Analysis'));
      console.log(chalk.gray(`   Build path: ${build.buildPath}`));
      console.log(chalk.gray(`   Total bundle size: ${chalk.white(formatBytes(build.totalSize))}`));
      
      // Bundle breakdown
      console.log(chalk.gray('\n   Bundle breakdown:'));
      const breakdown = build.bundleBreakdown;
      if (breakdown.javascript > 0) console.log(chalk.yellow(`      JavaScript: ${formatBytes(breakdown.javascript)}`));
      if (breakdown.images > 0) console.log(chalk.blue(`      Images: ${formatBytes(breakdown.images)}`));
      if (breakdown.fonts > 0) console.log(chalk.green(`      Fonts: ${formatBytes(breakdown.fonts)}`));
      if (breakdown.maps > 0) console.log(chalk.gray(`      Source maps: ${formatBytes(breakdown.maps)}`));
      if (breakdown.other > 0) console.log(chalk.white(`      Other: ${formatBytes(breakdown.other)}`));
      
      // Largest files
      if (build.largestFiles.length > 0) {
        console.log(chalk.gray('\n   Largest files (top 15):'));
        build.largestFiles.forEach(file => {
          const sizeColor = file.size > 1024 * 1024 ? chalk.red : file.size > 500 * 1024 ? chalk.yellow : chalk.gray;
          console.log(chalk.gray(`      ${file.path} - ${sizeColor(formatBytes(file.size))}`));
        });
      }
      
      // Dependencies analysis
      if (build.dependencies.length > 0) {
        console.log(chalk.gray('\n   Large dependencies (top 15):'));
        build.dependencies.forEach(dep => {
          const sizeColor = dep.size > 5 * 1024 * 1024 ? chalk.red : dep.size > 1024 * 1024 ? chalk.yellow : chalk.gray;
          console.log(chalk.gray(`      ${dep.name} - ${sizeColor(formatBytes(dep.size))} (${dep.files} files)`));
        });
      }
      
      printSeparator();
    }
    
    // Package Analysis
    if (result.packageAnalysis) {
      const pkg = result.packageAnalysis;
      console.log(chalk.cyan.bold('📦 Package Analysis'));
      
      // Unused packages
      if (pkg.unusedPackages.length > 0) {
        console.log(chalk.red.bold('\n   🗑️  Unused Packages'));
        console.log(chalk.gray(`   Found ${pkg.unusedPackages.length} unused package(s):`));
        let totalWastedSize = 0;
        pkg.unusedPackages.forEach(pack => {
          totalWastedSize += pack.size;
          const sizeColor = pack.size > 1024 * 1024 ? chalk.red : pack.size > 100 * 1024 ? chalk.yellow : chalk.gray;
          console.log(chalk.red(`      📦 ${pack.name}@${pack.version} ${chalk.gray(`(${pack.type})`)} - ${sizeColor(pack.estimatedSize || formatBytes(pack.size))}`));
        });
        console.log(chalk.gray(`   Total wasted space: ${chalk.red.bold(formatBytes(totalWastedSize))}`));
      } else {
        console.log(chalk.green('\n   ✅ No unused packages found'));
      }
      
      // Deprecated packages
      if (pkg.deprecatedPackages.length > 0) {
        console.log(chalk.yellow.bold('\n   ⚠️  Deprecated Packages'));
        console.log(chalk.gray(`   Found ${pkg.deprecatedPackages.length} deprecated package(s):`));
        pkg.deprecatedPackages.forEach(pack => {
          console.log(chalk.yellow(`      ⚠️  ${pack.name}@${pack.version} ${chalk.gray(`(${pack.type})`)}`));
          if (pack.deprecatedMessage) {
            console.log(chalk.gray(`         ${pack.deprecatedMessage}`));
          }
          if (pack.suggestedReplacement) {
            console.log(chalk.blue(`         💡 Suggested: ${pack.suggestedReplacement}`));
          }
        });
      } else {
        console.log(chalk.green('\n   ✅ No deprecated packages found'));
      }
      
      printSeparator();
    }
    
    // Suggestions
    if (result.suggestions.length > 0) {
      console.log(chalk.blue.bold('💡 Suggestions'));
      result.suggestions.forEach(suggestion => {
        console.log(chalk.blue(`   • ${suggestion}`));
      });
      printSeparator();
    }
    
    // Summary
    const totalIssues = result.unusedImports.length + result.unusedFiles.length;
    if (totalIssues === 0) {
      console.log(chalk.green.bold('🎉 Excellent! Your project is well optimized!'));
    } else {
      console.log(chalk.yellow.bold(`📋 Summary: ${totalIssues} optimization opportunity(ies) found`));
    }
    
    // Save JSON report if requested
    if (options.output) {
      try {
        fs.writeFileSync(options.output, JSON.stringify(result, null, 2));
        console.log(chalk.gray(`\n📄 JSON report saved to: ${options.output}`));
      } catch (error) {
        console.log(chalk.red(`\n❌ Failed to save JSON report: ${error}`));
      }
    }
    
    // Generate HTML report by default (unless explicitly disabled)
    if (options.html !== false) {
      try {
        const htmlPath = options.htmlPath || undefined;
        const reportPath = generateHtmlReport(result, projectPath, htmlPath);
        console.log(chalk.gray(`\n🌐 HTML report generated: ${reportPath}`));
        
        // Auto-open in browser by default (unless explicitly disabled)
        if (options.open !== false) {
          const command = process.platform === 'darwin' ? 'open' : 
                        process.platform === 'win32' ? 'start' : 'xdg-open';
          
          exec(`${command} "${reportPath}"`, (error) => {
            if (error) {
              console.log(chalk.yellow(`\n⚠️ Could not auto-open browser: ${error.message}`));
              console.log(chalk.gray(`Please manually open: ${reportPath}`));
            } else {
              console.log(chalk.green(`\n🚀 HTML report opened in browser!`));
            }
          });
        }
      } catch (error) {
        console.log(chalk.red(`\n❌ Failed to generate HTML report: ${error}`));
      }
    } else {
      console.log(chalk.gray(`\n📄 HTML report generation skipped (use default or remove --no-html to generate)`));
    }
    
    console.log(chalk.gray(`\n🕐 Report generated at: ${result.reportGeneratedAt.toLocaleString()}`));
    console.log('');
  });

program.parse();
